### ISSUE TITLE
URL routes and spreadsheet definitions

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#2]
We may end up having many different layouts, for example if we have these layouts:

mansion
layout2
layout3
layout4

Each layout would it's own Google spreadsheet, such as

mansion-spreadsheet
layout2-spreadsheet
layout3-spreadsheet
layout4-spreadsheet

Then, in a spreadsheet, it would have different tabs for each page. The default page would be index, so it would have an index tab, this page could be accessed using a url like:

domain.com/mansion/index

or just

domain.com/mansion

Whichever is easier

For other pages, they would have their own tabs in a spreadsheet, so, for example, if there we have a page5, it would have a page5 in the mansion-spreadsheet and then would be accessed like:

domain.com/mansion/page5

**Comment by stacksavings** [comment]
@barbosa89 Is this done?

**Comment by barbosa89** [comment]
In the configuration .env file, a value called DEFAULT_LAYOUT was created, this value corresponds to the default layout:

`DEFAULT_LAYOUT=mansion`

In this case the Mansion layout. 

In order to organize the routes of each layout, a route file will be created for each layout, in this case, a file called mansion.php was created in routes/mansion.php.

When the DEFAULT_LAYOUT setting is read, it will match the path file name mansion.php and it will be loaded.

```
# env('DEFAULT_LAYOUT'): Reading configuration value of default layout

Route::get('/', function () {
    return redirect(env('DEFAULT_LAYOUT') . '/index');
});

require __DIR__ . '/' . env('DEFAULT_LAYOUT') . '.php';

```

When you change the value of DEFAULT_LAYOUT, the routes of another layout will be loaded.

Within each route file of each layout, route groups will be used with the name of the layout as a prefix;

```
# mansion.php file

Route::group(['prefix' => 'mansion'], function()
{
    Route::get('index', 'MansionController@index');
});
```
